/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;

import java.io.BufferedReader;
import javax.swing.ImageIcon;

/**
 *
 * @author George
 */
public class BilanganPrima extends javax.swing.JFrame {

    /**
     * Creates new form BilanganPrima
     */
    public BilanganPrima() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        tombol_balik = new javax.swing.JLabel();
        input_user = new javax.swing.JTextField();
        tombol_klik = new javax.swing.JButton();
        scroll_pane = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 300));
        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 153, 51));
        judul.setText("BILANGAN PRIMA");
        jPanel1.add(judul);
        judul.setBounds(140, 30, 205, 33);

        tombol_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tombol_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombol_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombol_balikMousePressed(evt);
            }
        });
        jPanel1.add(tombol_balik);
        tombol_balik.setBounds(20, 10, 70, 90);

        input_user.setBackground(new java.awt.Color(254, 254, 214));
        input_user.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        input_user.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(input_user);
        input_user.setBounds(130, 80, 220, 30);

        tombol_klik.setBackground(new java.awt.Color(254, 254, 214));
        tombol_klik.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        tombol_klik.setForeground(new java.awt.Color(255, 153, 51));
        tombol_klik.setText("OK");
        tombol_klik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_klikActionPerformed(evt);
            }
        });
        jPanel1.add(tombol_klik);
        tombol_klik.setBounds(190, 130, 110, 25);

        scroll_pane.setBackground(new java.awt.Color(255, 153, 51));
        scroll_pane.setForeground(new java.awt.Color(255, 153, 51));

        hasil.setEditable(false);
        hasil.setBackground(new java.awt.Color(254, 254, 214));
        hasil.setColumns(20);
        hasil.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        hasil.setForeground(new java.awt.Color(153, 153, 153));
        hasil.setRows(5);
        scroll_pane.setViewportView(hasil);

        jPanel1.add(scroll_pane);
        scroll_pane.setBounds(70, 170, 350, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(451, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseEntered

    private void tombol_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseExited

    private void tombol_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMousePressed
        OTHERS objTampilNewJFrame = new OTHERS();
        objTampilNewJFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tombol_balikMousePressed

    private void tombol_klikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_klikActionPerformed
        String k;
        try{
            k =input_user.getText();
            int d = Integer.parseInt(k);
            int temp = 0;
            String awkrd = "";
            for (int i=1; i<d; i++){
                for(int j=1;j<=i;j++){
                    if(i%j==0){
                        temp++;
                    }
                }
                if(temp==2){
                    awkrd = awkrd + i + " Bilangan Prima!\n";
                    hasil.setText(awkrd); 
                }
                temp = 0;
            }
        }catch(Exception ex){}
    }//GEN-LAST:event_tombol_klikActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){ 
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try 
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BilanganPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BilanganPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BilanganPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BilanganPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BilanganPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea hasil;
    private javax.swing.JTextField input_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JScrollPane scroll_pane;
    private javax.swing.JLabel tombol_balik;
    private javax.swing.JButton tombol_klik;
    // End of variables declaration//GEN-END:variables
}
