/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dumasi Ekel
 */
public class KonversiSatuanWaktu extends javax.swing.JFrame implements KonversiSatuanWaktuInterface {

    /**
     * Creates new form KonversiSatuanWaktu
     */
    public KonversiSatuanWaktu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        output = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        reset = new javax.swing.JButton();
        convert = new javax.swing.JButton();
        tombol_balik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 153, 51));
        judul.setText("KONVERSI SATUAN WAKTU");
        jPanel1.add(judul);
        judul.setBounds(160, 30, 320, 50);

        input.setBackground(new java.awt.Color(254, 254, 214));
        input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel1.add(input);
        input.setBounds(70, 110, 340, 40);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEKON", "MENIT", "JAM", "HARI", "MINGGU", "BULAN", "TAHUN" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(430, 110, 120, 40);

        output.setEditable(false);
        output.setBackground(new java.awt.Color(242, 242, 196));
        output.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(output);
        output.setBounds(70, 170, 340, 40);

        jComboBox2.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEKON", "MENIT", "JAM", "HARI", "MINGGU", "BULAN", "TAHUN" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(430, 170, 120, 40);

        reset.setBackground(new java.awt.Color(254, 254, 214));
        reset.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(150, 240, 140, 40);

        convert.setBackground(new java.awt.Color(254, 254, 214));
        convert.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        jPanel1.add(convert);
        convert.setBounds(330, 240, 140, 40);

        tombol_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tombol_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombol_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombol_balikMousePressed(evt);
            }
        });
        jPanel1.add(tombol_balik);
        tombol_balik.setBounds(20, 20, 70, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 300);

        setSize(new java.awt.Dimension(610, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        prosesKonversiSatuanWaktu();
    }//GEN-LAST:event_convertActionPerformed
    @Override
    public void prosesKonversiSatuanWaktu(){

        String statement;
        try{
            statement = input.getText();
            long k = Integer.parseInt(statement);
            /*#1
            ===========================================================================================================
            KEMBALI KE DIRI MASING MASING
            ==============================================================================================================
            */
            if(jComboBox1.getSelectedItem().equals("SEKON") && jComboBox2.getSelectedItem().equals("SEKON")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("MENIT") && jComboBox2.getSelectedItem().equals("MENIT")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("JAM") && jComboBox2.getSelectedItem().equals("JAM")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("HARI") && jComboBox2.getSelectedItem().equals("HARI")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("MINGGU") && jComboBox2.getSelectedItem().equals("MINGGU")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("BULAN") && jComboBox2.getSelectedItem().equals("BULAN")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("TAHUN") && jComboBox2.getSelectedItem().equals("TAHUN")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            /*#2
            ===========================================================================================================
            SEKON ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("SEKON") && jComboBox2.getSelectedItem().equals("MENIT")){
                double hasil2 = k / 60f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("SEKON") && jComboBox2.getSelectedItem().equals("JAM")){
                double hasil2 = k / 3600f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("SEKON") && jComboBox2.getSelectedItem().equals("HARI")){
                double hasil2 = k / 86400f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("SEKON") && jComboBox2.getSelectedItem().equals("MINGGU")){
                double hasil2 = k / 604800f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("SEKON") && jComboBox2.getSelectedItem().equals("BULAN")){
                double hasil2 = k / 2419200f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("SEKON") && jComboBox2.getSelectedItem().equals("TAHUN")){
                double hasil2 = k / 29030400f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            /*#3
            ===========================================================================================================
            MENIT  ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("MENIT") && jComboBox2.getSelectedItem().equals("SEKON")){
                long hasil2 = k * 60l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MENIT") && jComboBox2.getSelectedItem().equals("JAM")){
                double hasil2 = k / 60f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MENIT") && jComboBox2.getSelectedItem().equals("HARI")){
                double hasil2 = k / 1440f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MENIT") && jComboBox2.getSelectedItem().equals("MINGGU")){
                double hasil2 = k / 10080f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MENIT") && jComboBox2.getSelectedItem().equals("BULAN")){
                double hasil2 = k / 40320f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }            
            else if(jComboBox1.getSelectedItem().equals("MENIT") && jComboBox2.getSelectedItem().equals("TAHUN")){
                double hasil2 = k / 483840f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            /*#4
            ===========================================================================================================
            JAM  ==> SEMUA 
            ==============================================================================================================
            */            
            else if(jComboBox1.getSelectedItem().equals("JAM") && jComboBox2.getSelectedItem().equals("SEKON")){
                long hasil2 = k * 3600l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("JAM") && jComboBox2.getSelectedItem().equals("MENIT")){
                long hasil2 = k * 60l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("JAM") && jComboBox2.getSelectedItem().equals("HARI")){
                double hasil2 = k / 24f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("JAM") && jComboBox2.getSelectedItem().equals("MINGGU")){
                double hasil2 = k / 168f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("JAM") && jComboBox2.getSelectedItem().equals("BULAN")){
                double hasil2 = k / 672f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("JAM") && jComboBox2.getSelectedItem().equals("TAHUN")){
                double hasil2 = k / 8064f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            /*#5
            ===========================================================================================================
            HARI  ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("HARI") && jComboBox2.getSelectedItem().equals("SEKON")){
                long hasil2 = k * 86400l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HARI") && jComboBox2.getSelectedItem().equals("MENIT")){
                long hasil2 = k * 1440l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HARI") && jComboBox2.getSelectedItem().equals("JAM")){
                long hasil2 = k * 24l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HARI") && jComboBox2.getSelectedItem().equals("MINGGU")){
                double hasil2 = k / 7f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HARI") && jComboBox2.getSelectedItem().equals("BULAN")){
                double hasil2 = k / 30f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HARI") && jComboBox2.getSelectedItem().equals("TAHUN")){
                double hasil2 = k / 365f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }            
            /*#6
            ===========================================================================================================
            MINGGU  ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("MINGGU") && jComboBox2.getSelectedItem().equals("SEKON")){
                long hasil2 = k * 604800l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MINGGU") && jComboBox2.getSelectedItem().equals("MENIT")){
                long hasil2 = k * 10080l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MINGGU") && jComboBox2.getSelectedItem().equals("JAM")){
                long hasil2 = k * 168l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MINGGU") && jComboBox2.getSelectedItem().equals("HARI")){
                long hasil2 = k * 7l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MINGGU") && jComboBox2.getSelectedItem().equals("BULAN")){
                double hasil2 = k / 4f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MINGGU") && jComboBox2.getSelectedItem().equals("TAHUN")){
                double hasil2 = k / 48f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }            
            /*#7
            ===========================================================================================================
            BULAN  ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("BULAN") && jComboBox2.getSelectedItem().equals("SEKON")){
                long hasil2 = k * 2419200; 
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BULAN") && jComboBox2.getSelectedItem().equals("MENIT")){
                long hasil2 = k * 40320l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BULAN") && jComboBox2.getSelectedItem().equals("JAM")){
                long hasil2 = k * 672l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BULAN") && jComboBox2.getSelectedItem().equals("HARI")){
                long hasil2 = k * 30l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BULAN") && jComboBox2.getSelectedItem().equals("MINGGU")){
                long hasil2 = k * 4l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BULAN") && jComboBox2.getSelectedItem().equals("TAHUN")){
                double hasil2 = k / 12f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }            
            /*#8
            ===========================================================================================================
            TAHUN  ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("TAHUN") && jComboBox2.getSelectedItem().equals("SEKON")){
                long hasil2 = k * 29030400l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("TAHUN") && jComboBox2.getSelectedItem().equals("MENIT")){
                long hasil2 = k * 483840l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("TAHUN") && jComboBox2.getSelectedItem().equals("JAM")){
                long hasil2 = k * 8064l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("TAHUN") && jComboBox2.getSelectedItem().equals("HARI")){
                long hasil2 = k * 365l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("TAHUN") && jComboBox2.getSelectedItem().equals("MINGGU")){
                long hasil2 = k * 48l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("TAHUN") && jComboBox2.getSelectedItem().equals("BULAN")){
                long hasil2 = k * 12l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            //==========================================================================            
            else{
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan."); 
                input.setText(null);
                output.setText(null);
                jComboBox1.setSelectedItem("SEKON");
                jComboBox2.setSelectedItem("SEKON");
            }
        }catch(NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan.\nDilarang menggunakan karakter untuk memasukkan nilai,\ntidak memasukkan apapun,\natau memasukan jumlah diluar batas.");            
                input.setText(null);
                output.setText(null);
                jComboBox1.setSelectedItem("SEKON");
                jComboBox2.setSelectedItem("SEKON");
        }    
    }
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        input.setText(null);
        output.setText(null);
        jComboBox1.setSelectedItem("SEKON");
        jComboBox2.setSelectedItem("SEKON");
    }//GEN-LAST:event_resetActionPerformed

    private void tombol_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseEntered

    private void tombol_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseExited

    private void tombol_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMousePressed
        Mnu_Utama objTampilNewJFrame = new Mnu_Utama();
        objTampilNewJFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tombol_balikMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanWaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSatuanWaktu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JTextField input;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JTextField output;
    private javax.swing.JButton reset;
    private javax.swing.JLabel tombol_balik;
    // End of variables declaration//GEN-END:variables
}
