/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dumasi Ekel
 */
public class KonversiSatuanVolum extends KonversiSatuanVolumPewarisan {

    /**
     * Creates new form KonversiSatuanVolum
     */
    public KonversiSatuanVolum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        reset = new javax.swing.JButton();
        convert = new javax.swing.JButton();
        tombol_balik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel2.setLayout(null);

        judul.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 153, 51));
        judul.setText("KONVERSI SATUAN VOLUM");
        jPanel2.add(judul);
        judul.setBounds(150, 40, 330, 33);

        input.setBackground(new java.awt.Color(254, 254, 214));
        input.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        jPanel2.add(input);
        input.setBounds(80, 110, 340, 40);

        output.setEditable(false);
        output.setBackground(new java.awt.Color(242, 242, 196));
        output.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(output);
        output.setBounds(80, 170, 340, 40);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM3", "HM3", "DAM3", "M3", "DM3", "CM3", "MM3" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(450, 110, 80, 40);

        jComboBox2.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM3", "HM3", "DAM3", "M3", "DM3", "CM3", "MM3" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(450, 170, 80, 40);

        reset.setBackground(new java.awt.Color(254, 254, 214));
        reset.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(170, 240, 140, 40);

        convert.setBackground(new java.awt.Color(254, 254, 214));
        convert.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        jPanel2.add(convert);
        convert.setBounds(340, 240, 140, 40);

        tombol_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tombol_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombol_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombol_balikMousePressed(evt);
            }
        });
        jPanel2.add(tombol_balik);
        tombol_balik.setBounds(20, 20, 70, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 610, 300);

        setSize(new java.awt.Dimension(610, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        input.setText(null);
        output.setText(null);
        jComboBox1.setSelectedItem("KM3");
        jComboBox2.setSelectedItem("KM3");     
    }//GEN-LAST:event_resetActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        prosesKonversiSatuanVolum();
    }//GEN-LAST:event_convertActionPerformed
    @Override
    public void prosesKonversiSatuanVolum(){

        String statement;
        try{
            statement = input.getText();
            int k = Integer.parseInt(statement);
            /*#1
            ===========================================================================================================
            KEMBALI KE DIRI MASING MASING
            ==============================================================================================================
            */
            if(jComboBox1.getSelectedItem().equals("KM3") && jComboBox2.getSelectedItem().equals("KM3")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("HM3") && jComboBox2.getSelectedItem().equals("HM3")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("DAM3") && jComboBox2.getSelectedItem().equals("DAM3")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("M3") && jComboBox2.getSelectedItem().equals("M3")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("DM3") && jComboBox2.getSelectedItem().equals("DM3")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("CM3") && jComboBox2.getSelectedItem().equals("CM3")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("MM3") && jComboBox2.getSelectedItem().equals("MM3")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            /*#2
            ===========================================================================================================
            KM ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("KM3") && jComboBox2.getSelectedItem().equals("HM3")){
                long hasil2 = k * 1000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("KM3") && jComboBox2.getSelectedItem().equals("DAM3")){
                long hasil2 = k * 10000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("KM3") && jComboBox2.getSelectedItem().equals("M3")){
                long hasil2 = k * 100000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("KM3") && jComboBox2.getSelectedItem().equals("DM3")){
                long hasil2 = k * 1000000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("KM3") && jComboBox2.getSelectedItem().equals("CM3")){
                long hasil2 = k * 10000000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("KM3") && jComboBox2.getSelectedItem().equals("MM3")){
                long hasil2 = k * 100000000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            /*#3
            ============================================================================================================
            HM ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("HM3") && jComboBox2.getSelectedItem().equals("KM3")){
                double hasil1 = k / 1000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HM3") && jComboBox2.getSelectedItem().equals("DAM3")){
                long hasil2 = k * 1000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HM3") && jComboBox2.getSelectedItem().equals("M3")){
                long hasil2 = k * 10000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HM3") && jComboBox2.getSelectedItem().equals("DM3")){
                long hasil2 = k * 100000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("HM3") && jComboBox2.getSelectedItem().equals("CM3")){
                long hasil2 = k * 1000000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("HM3") && jComboBox2.getSelectedItem().equals("MM3")){
                long hasil2 = k * 10000000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            /*#4
            ============================================================================================================
            DAM ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("DAM3") && jComboBox2.getSelectedItem().equals("KM3")){
                double hasil1 = k / 10000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DAM3") && jComboBox2.getSelectedItem().equals("HM3")){
                double hasil1 = k / 1000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DAM3") && jComboBox2.getSelectedItem().equals("M3")){
                long hasil2 = k * 1000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DAM3") && jComboBox2.getSelectedItem().equals("DM3")){
                long hasil2 = k * 10000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DAM3") && jComboBox2.getSelectedItem().equals("CM3")){
                long hasil2 = k * 100000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("DAM3") && jComboBox2.getSelectedItem().equals("MM3")){
                long hasil2 = k * 1000000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            /*#4
            ============================================================================================================
            M ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("M3") && jComboBox2.getSelectedItem().equals("KM3")){
                double hasil1 = k / 100000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("M3") && jComboBox2.getSelectedItem().equals("HM3")){
                double hasil1 = k / 10000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("M3") && jComboBox2.getSelectedItem().equals("DAM3")){
                double hasil1 = k / 1000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("M3") && jComboBox2.getSelectedItem().equals("DM3")){
                long hasil2 = k * 1000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("M3") && jComboBox2.getSelectedItem().equals("CM3")){
                long hasil2 = k * 10000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("M3") && jComboBox2.getSelectedItem().equals("MM3")){
                long hasil2 = k * 100000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        

            /*#5
            ============================================================================================================
            DM ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("DM3") && jComboBox2.getSelectedItem().equals("KM3")){
                double hasil1 = k / 1000000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DM3") && jComboBox2.getSelectedItem().equals("HM3")){
                double hasil1 = k / 100000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DM3") && jComboBox2.getSelectedItem().equals("DAM3")){
                double hasil1 = k / 10000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DM3") && jComboBox2.getSelectedItem().equals("M3")){
                double hasil1 = k / 1000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("DM3") && jComboBox2.getSelectedItem().equals("CM3")){
                long hasil2 = k * 1000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("DM3") && jComboBox2.getSelectedItem().equals("MM3")){
                long hasil2 = k * 10000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        

            /*#6
            ============================================================================================================
            CM ==> SEMUA   
            ============================================================================================================        
            */

            else if(jComboBox1.getSelectedItem().equals("CM3") && jComboBox2.getSelectedItem().equals("KM3")){
                double hasil1 = k / 10000000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("CM3") && jComboBox2.getSelectedItem().equals("HM3")){
                double hasil1 = k / 1000000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("CM3") && jComboBox2.getSelectedItem().equals("DAM3")){
                double hasil1 = k / 100000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("CM3") && jComboBox2.getSelectedItem().equals("M3")){
                double hasil1 = k / 10000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("CM3") && jComboBox2.getSelectedItem().equals("DM3")){
                double hasil1 = k / 1000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("CM3") && jComboBox2.getSelectedItem().equals("MM3")){
                long hasil2 = k * 1000l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }        
            /*#7
            ============================================================================================================
            MM ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("MM3") && jComboBox2.getSelectedItem().equals("KM3")){
                double hasil1 = k / 100000000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MM3") && jComboBox2.getSelectedItem().equals("HM3")){
                double hasil1 = k / 10000000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MM3") && jComboBox2.getSelectedItem().equals("DAM3")){
                double hasil1 = k / 1000000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MM3") && jComboBox2.getSelectedItem().equals("M3")){
                double hasil1 = k / 100000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("MM3") && jComboBox2.getSelectedItem().equals("DM3")){
                double hasil1 = k / 10000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("MM3") && jComboBox2.getSelectedItem().equals("CM3")){
                double hasil1 = k / 1000f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else{
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan."); 
                 input.setText(null);
                 output.setText(null);
                 jComboBox1.setSelectedItem("KM3");
                 jComboBox2.setSelectedItem("KM3");    
            }
        }catch(NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan.\nDilarang menggunakan karakter untuk memasukkan nilai,\ntidak memasukkan apapun,\natau memasukan jumlah diluar batas."); 
                input.setText(null);
                output.setText(null);
                jComboBox1.setSelectedItem("KM3");
                jComboBox2.setSelectedItem("KM3");     
        }
/*

=================================================(PEMISAH)==========================================================        
     
*/    
    }
    private void tombol_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMousePressed
        Mnu_Utama objTampilNewJFrame = new Mnu_Utama();
        objTampilNewJFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tombol_balikMousePressed

    private void tombol_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseEntered

    private void tombol_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanVolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanVolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanVolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanVolum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSatuanVolum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JTextField input;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel judul;
    private javax.swing.JTextField output;
    private javax.swing.JButton reset;
    private javax.swing.JLabel tombol_balik;
    // End of variables declaration//GEN-END:variables
}
