/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dumasi Ekel
 */
public class KonversiUang extends KonversiUangAbstract {

    /**
     * Creates new form KonversiSatuanMassa
     */
    public KonversiUang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        convert = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        tombol_balik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("KONVERSI UANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 30, 200, 50);

        input.setBackground(new java.awt.Color(254, 254, 214));
        input.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(input);
        input.setBounds(50, 110, 340, 40);

        output.setEditable(false);
        output.setBackground(new java.awt.Color(242, 242, 196));
        output.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });
        jPanel1.add(output);
        output.setBounds(50, 170, 340, 40);

        jComboBox2.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUPIAH", "YEN", "RINGGIT", "RIYAL", "POUND", "USD", "BIRR", "YUAN", "RUBEL" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(410, 170, 140, 40);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUPIAH", "YEN", "RINGGIT", "RIYAL", "POUND", "USD", "BIRR", "YUAN", "RUBEL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(410, 110, 140, 40);

        convert.setBackground(new java.awt.Color(254, 254, 214));
        convert.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        jPanel1.add(convert);
        convert.setBounds(320, 240, 140, 40);

        reset.setBackground(new java.awt.Color(254, 254, 214));
        reset.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(160, 240, 140, 40);

        tombol_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tombol_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombol_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombol_balikMousePressed(evt);
            }
        });
        jPanel1.add(tombol_balik);
        tombol_balik.setBounds(20, 20, 70, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 300);

        setSize(new java.awt.Dimension(610, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        prosesKonversiUang();
    }//GEN-LAST:event_convertActionPerformed
    @Override
    public void prosesKonversiUang(){

        String statement;
        try{
            statement = input.getText();
            int k = Integer.parseInt(statement);
            /*#1
            ===========================================================================================================
            KEMBALI KE DIRI MASING MASING
            ==============================================================================================================
            */
            if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("YEN")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("RIYAL")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("POUND")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("USD")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("YUAN")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("RUBEL")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }   
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("BIRR")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }               
            /*#2
            ===========================================================================================================
            RUPIAH ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("YEN")){
                double hasil2 = k * 0.00845f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                double hasil2 = k * 0.00033f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("RIYAL")){
                double hasil2 = k * 0.00029;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("POUND")){
                double hasil2 = k * 0.00006f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("USD")){
                double hasil2 = k * 0.00007f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }       
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("YUAN")){
                double hasil2 = k * 0.00051f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("RUBEL")){
                double hasil2 = k * 0.00497f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUPIAH") && jComboBox2.getSelectedItem().equals("BIRR")){
                double hasil2 = k * 0.00177f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }            
            /*#3
            ============================================================================================================
            YEN ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                double hasil1 = k * 118.40748f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                double hasil1 = k * 0.03921f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("RIYAL")){
                double hasil1 = k * 0.03412f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("POUND")){
                double hasil1 = k * 0.00715f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("USD")){
                double hasil1 = k * 0.00882f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("YUAN")){
                double hasil1 = k * 0.06061f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("RUBEL")){
                double hasil1 = k * 0.58802f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YEN") && jComboBox2.getSelectedItem().equals("BIRR")){
                double hasil1 = k * 0.20938f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }            
            /*#4
            ============================================================================================================
            RINGGIT ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                double hasil1 = k * 3019.89823f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("YEN")){
                double hasil1 = k * 25.50429f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("RIYAL")){
                double hasil1 = k * 0.82017f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("POUND")){
                double hasil1 = k * 0.18238f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("USD")){
                double hasil1 = k * 0.22495f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }       
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("YUAN")){
                double hasil1 = k * 1.54571f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("RUBEL")){
                double hasil1 = k * 14.99715f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RINGGIT") && jComboBox2.getSelectedItem().equals("BIRR")){
                double hasil1 = k * 5.34009f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }            
            /*#4
            ============================================================================================================
            RIYAL ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                double hasil1 = k * 3470.25677f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("YEN")){
                double hasil1 = k * 29.30775f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                double hasil1 = k * 1.14913;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("POUND")){
                double hasil1 = k * 0.20958f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("USD")){
                double hasil1 = k * 0.2585f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }      
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("YUAN")){
                double hasil1 = k * 1.77622f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("RUBEL")){
                double hasil1 = k * 17.23368f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RIYAL") && jComboBox2.getSelectedItem().equals("BIRR")){
                double hasil1 = k * 6.13646f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }            

            /*#5
            ============================================================================================================
            POUND ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                float hasil1 = k * 16558f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("YEN")){
                float hasil1 = k * 139f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("RIYAL")){
                float hasil1 = k * 4.7f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                float hasil1 = k * 5.4f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("USD")){
                float hasil1 = k * 1.23f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }       
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("YUAN")){
                float hasil1 = k * 8.4f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("RUBEL")){
                float hasil1 = k * 82.2f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("POUND") && jComboBox2.getSelectedItem().equals("BIRR")){
                float hasil1 = k * 29.28f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }            
            /*#6
            ============================================================================================================
            USD ==> SEMUA   
            ============================================================================================================        
            */

            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                float hasil1 = k * 13424.5f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("YEN")){
                float hasil1 = k * 113.37f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                float hasil1 = k * 4.44f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("POUND")){
                float hasil1 = k * 0.81f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("YUAN")){
                float hasil1 = k * 6.87f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }     
            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("RUBEL")){
                float hasil1 = k * 66f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("USD") && jComboBox2.getSelectedItem().equals("BIRR")){
                float hasil1 = k * 23.73f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }            
            /*#7
            ============================================================================================================
            YUAN ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                float hasil1 = k * 1953.7f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                float hasil1 = k * 6.64f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("YEN")){
                float hasil1 = k * 16.5f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("RIYAL")){
                float hasil1 = k * 0.56f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("POUND")){
                float hasil1 = k * 0.117f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }    
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("USD")){
                float hasil1 = k * 0.14f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("RUBEL")){
                float hasil1 = k * 9.702f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("YUAN") && jComboBox2.getSelectedItem().equals("BIRR")){
                float hasil1 = k * 3.454f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }            
            /*#8
            ============================================================================================================
            RUBEL ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                float hasil1 = k * 201.364f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                float hasil1 = k * 0.06f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("YEN")){
                float hasil1 = k * 1.700f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("RIYAL")){
                float hasil1 = k * 0.058f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("POUND")){
                float hasil1 = k * 0.012f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("USD")){
                float hasil1 = k * 0.015f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("YUAN")){
                float hasil1 = k * 0.103f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("RUBEL") && jComboBox2.getSelectedItem().equals("BIRR")){
                float hasil1 = k * 0.350f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }            
            /*#9
            ============================================================================================================
            BIRR ==> SEMUA   
            ============================================================================================================        
            */            
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("RUPIAH")){
                float hasil1 = k * 565.51f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("RINGGIT")){
                float hasil1 = k * 0.187f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("YEN")){
                float hasil1 = k * 4.776f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("RIYAL")){
                float hasil1 = k * 0.16f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("POUND")){
                float hasil1 = k * 0.034f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("USD")){
                float hasil1 = k * 0.04f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("YUAN")){
                float hasil1 = k * 0.28f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("BIRR") && jComboBox2.getSelectedItem().equals("RUBEL")){
                float hasil1 = k * 2.808f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            //========================================================================================================
            else{
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan."); 
                input.setText(null);
                output.setText(null);
                jComboBox1.setSelectedItem("KG");
                jComboBox2.setSelectedItem("KG");
            }
        }catch(NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan.\nDilarang menggunakan karakter untuk memasukkan nilai,\ntidak memasukkan apapun,\natau memasukan jumlah diluar batas.");            
                input.setText(null);
                output.setText(null);
                jComboBox1.setSelectedItem("KG");
                jComboBox2.setSelectedItem("KG");
        }
/*

=================================================(PEMISAH)==========================================================        
     
*/    
    
    }
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        input.setText(null);
        output.setText(null);
        jComboBox1.setSelectedItem("KG");
        jComboBox2.setSelectedItem("KG");
    }//GEN-LAST:event_resetActionPerformed

    private void tombol_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMousePressed
        Mnu_Utama objTampilNewJFrame = new Mnu_Utama();
        objTampilNewJFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tombol_balikMousePressed

    private void tombol_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseExited

    private void tombol_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiUang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiUang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JTextField input;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField output;
    private javax.swing.JButton reset;
    private javax.swing.JLabel tombol_balik;
    // End of variables declaration//GEN-END:variables
}
