/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dumasi Ekel
 */
public class KonversiSatuanJumlah extends javax.swing.JFrame implements KonversiSatuanJumlahInterface {

    /**
     * Creates new form KonversiSatuanJumlah
     */
    public KonversiSatuanJumlah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        combo_input = new javax.swing.JComboBox<>();
        combo_output = new javax.swing.JComboBox<>();
        input1 = new javax.swing.JTextField();
        output1 = new javax.swing.JTextField();
        combo_input1 = new javax.swing.JComboBox<>();
        combo_output1 = new javax.swing.JComboBox<>();
        convert_input = new javax.swing.JButton();
        convert_input1 = new javax.swing.JButton();
        reset_input = new javax.swing.JButton();
        reset_input1 = new javax.swing.JButton();
        tombol_balik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 153, 51));
        judul.setText("KONVERSI SATUAN JUMLAH");
        jPanel1.add(judul);
        judul.setBounds(240, 40, 330, 33);

        input.setBackground(new java.awt.Color(254, 254, 214));
        input.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(input);
        input.setBounds(80, 100, 170, 30);

        output.setEditable(false);
        output.setBackground(new java.awt.Color(242, 242, 196));
        output.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(output);
        output.setBounds(80, 150, 170, 30);

        combo_input.setBackground(new java.awt.Color(254, 254, 214));
        combo_input.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        combo_input.setForeground(new java.awt.Color(255, 153, 51));
        combo_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GROSS", "LUSIN", "BUAH" }));
        jPanel1.add(combo_input);
        combo_input.setBounds(260, 100, 110, 30);

        combo_output.setBackground(new java.awt.Color(254, 254, 214));
        combo_output.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        combo_output.setForeground(new java.awt.Color(255, 153, 51));
        combo_output.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GROSS", "LUSIN", "BUAH" }));
        jPanel1.add(combo_output);
        combo_output.setBounds(260, 150, 110, 30);

        input1.setBackground(new java.awt.Color(254, 254, 214));
        input1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        input1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(input1);
        input1.setBounds(390, 100, 170, 30);

        output1.setEditable(false);
        output1.setBackground(new java.awt.Color(242, 242, 196));
        output1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        output1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(output1);
        output1.setBounds(390, 150, 170, 30);

        combo_input1.setBackground(new java.awt.Color(254, 254, 214));
        combo_input1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        combo_input1.setForeground(new java.awt.Color(255, 153, 51));
        combo_input1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KODI", "RIM", "HELAI" }));
        jPanel1.add(combo_input1);
        combo_input1.setBounds(580, 100, 110, 30);

        combo_output1.setBackground(new java.awt.Color(254, 254, 214));
        combo_output1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        combo_output1.setForeground(new java.awt.Color(255, 153, 51));
        combo_output1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KODI", "RIM", "HELAI" }));
        jPanel1.add(combo_output1);
        combo_output1.setBounds(580, 150, 110, 30);

        convert_input.setBackground(new java.awt.Color(254, 254, 214));
        convert_input.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        convert_input.setText("CONVERT");
        convert_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_inputActionPerformed(evt);
            }
        });
        jPanel1.add(convert_input);
        convert_input.setBounds(230, 220, 130, 40);

        convert_input1.setBackground(new java.awt.Color(254, 254, 214));
        convert_input1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        convert_input1.setText("CONVERT");
        convert_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_input1ActionPerformed(evt);
            }
        });
        jPanel1.add(convert_input1);
        convert_input1.setBounds(540, 220, 130, 40);

        reset_input.setBackground(new java.awt.Color(254, 254, 214));
        reset_input.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        reset_input.setText("RESET");
        reset_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_inputActionPerformed(evt);
            }
        });
        jPanel1.add(reset_input);
        reset_input.setBounds(90, 220, 120, 40);

        reset_input1.setBackground(new java.awt.Color(254, 254, 214));
        reset_input1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        reset_input1.setText("RESET");
        reset_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_input1ActionPerformed(evt);
            }
        });
        jPanel1.add(reset_input1);
        reset_input1.setBounds(400, 220, 120, 40);

        tombol_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tombol_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombol_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombol_balikMousePressed(evt);
            }
        });
        jPanel1.add(tombol_balik);
        tombol_balik.setBounds(20, 10, 70, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 280);

        setSize(new java.awt.Dimension(770, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reset_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_input1ActionPerformed
        input1.setText(null);
        output1.setText(null);
        combo_input1.setSelectedItem("KODI");
        combo_output1.setSelectedItem("KODI");
    }//GEN-LAST:event_reset_input1ActionPerformed

    private void reset_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_inputActionPerformed
        input.setText(null);
        output.setText(null);
        combo_input.setSelectedItem("GROSS");
        combo_output.setSelectedItem("GROSS");
    }//GEN-LAST:event_reset_inputActionPerformed

    private void convert_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_inputActionPerformed
        prosesKonversiSatuanJumlahGross();
    }//GEN-LAST:event_convert_inputActionPerformed

    private void convert_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_input1ActionPerformed
        prosesKonversiSatuanJumlahKodi();
    }//GEN-LAST:event_convert_input1ActionPerformed
    @Override
    public void prosesKonversiSatuanJumlahGross(){

        String statement;
        try{
            statement = input.getText();
            long k = Integer.parseInt(statement);
            /*#1
            ===========================================================================================================
            KEMBALI KE DIRI MASING MASING (GROSS, LUSIN , BUAH)
            ==============================================================================================================
            */
            if(combo_input.getSelectedItem().equals("GROSS") && combo_output.getSelectedItem().equals("GROSS")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(combo_input.getSelectedItem().equals("LUSIN") && combo_output.getSelectedItem().equals("LUSIN")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(combo_input.getSelectedItem().equals("BUAH") && combo_output.getSelectedItem().equals("BUAH")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }               
            /*#2
            ===========================================================================================================
            GROSS ==> LUSIN, BUAH 
            ==============================================================================================================
            */
            else if(combo_input.getSelectedItem().equals("GROSS") && combo_output.getSelectedItem().equals("LUSIN")){
                long hasil2 = k * 12l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            else if(combo_input.getSelectedItem().equals("GROSS") && combo_output.getSelectedItem().equals("BUAH")){
                long hasil2 = k * 144l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            /*#3
            ===========================================================================================================
            LUSIN ==> GROSS, BUAH 
            ==============================================================================================================
            */
            else if(combo_input.getSelectedItem().equals("LUSIN") && combo_output.getSelectedItem().equals("GROSS")){
                double hasil2 = k / 12f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(combo_input.getSelectedItem().equals("LUSIN") && combo_output.getSelectedItem().equals("BUAH")){
                long hasil2 = k * 12l;
                String hasil = String.format("%d", hasil2);
                output.setText(hasil);
            }
            /*#4
            ===========================================================================================================
            BUAH ==> LUSIN, GROSS 
            ==============================================================================================================
            */
            else if(combo_input.getSelectedItem().equals("BUAH") && combo_output.getSelectedItem().equals("LUSIN")){
                double hasil2 = k / 12f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(combo_input.getSelectedItem().equals("BUAH") && combo_output.getSelectedItem().equals("GROSS")){
                double hasil2 = k / 144f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }            
            //==========================================================================           
            else{
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan."); 
                input.setText(null);
                output.setText(null);
                combo_input.setSelectedItem("GROSS");
                combo_output.setSelectedItem("GROSS");
            }
        }catch(NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan.\nDilarang menggunakan karakter untuk memasukkan nilai,\ntidak memasukkan apapun,\natau memasukan jumlah diluar batas.");            
                input.setText(null);
                output.setText(null);
                combo_input.setSelectedItem("GROSS");
                combo_output.setSelectedItem("GROSS");
        }
    }                                        
    @Override
    public void prosesKonversiSatuanJumlahKodi(){

        String statement;
        try{
            statement = input1.getText();
            long k = Integer.parseInt(statement);
            /*#1
            ===========================================================================================================
            KEMBALI KE DIRI MASING MASING (KODI, RIM, HELAI)
            ==============================================================================================================
            */       
            if(combo_input1.getSelectedItem().equals("KODI") && combo_output1.getSelectedItem().equals("KODI")){
                String hasil = String.format("%d", k);
                output1.setText(hasil);
            }        
            else if(combo_input1.getSelectedItem().equals("RIM") && combo_output1.getSelectedItem().equals("RIM")){
                String hasil = String.format("%d", k);
                output1.setText(hasil);
            }        
            else if(combo_input1.getSelectedItem().equals("HELAI") && combo_output1.getSelectedItem().equals("HELAI")){
                String hasil = String.format("%d", k);
                output1.setText(hasil);
            } 
            /*#2
            ===========================================================================================================
            RIM ==>KODI, HELAI
            ==============================================================================================================
            */
            else if(combo_input1.getSelectedItem().equals("RIM") && combo_output1.getSelectedItem().equals("HELAI")){
                long hasil2 = k * 500l; // 25 kodi = 500 helai
                String hasil = String.format("%d", hasil2);
                output1.setText(hasil);
            }
            else if(combo_input1.getSelectedItem().equals("RIM") && combo_output1.getSelectedItem().equals("KODI")){
                long hasil2 = k * 25l; 
                String hasil = String.format("%d", hasil2);
                output1.setText(hasil);
            }            
            /*#3
            ===========================================================================================================
            KODI ==>RIM, HELAI
            ==============================================================================================================
            */
            else if(combo_input1.getSelectedItem().equals("KODI") && combo_output1.getSelectedItem().equals("RIM")){
                double hasil2 = k / 25f; 
                String hasil = String.format("%f", hasil2);
                output1.setText(hasil);
            }
            else if(combo_input1.getSelectedItem().equals("KODI") && combo_output1.getSelectedItem().equals("HELAI")){
                long hasil2 = k * 20l; 
                String hasil = String.format("%d", hasil2);
                output1.setText(hasil);
            }
            /*#4
            ===========================================================================================================
            HELAI ==>KODI, RIM
            ==============================================================================================================
            */
            else if(combo_input1.getSelectedItem().equals("HELAI") && combo_output1.getSelectedItem().equals("KODI")){
                double hasil2 = k / 20f; 
                String hasil = String.format("%f", hasil2);
                output1.setText(hasil);
            }
            else if(combo_input1.getSelectedItem().equals("HELAI") && combo_output1.getSelectedItem().equals("RIM")){
                double hasil2 = k / 500f; 
                String hasil = String.format("%f", hasil2);
                output1.setText(hasil);
            }            
            //============================================================================================================== 
            else{
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan."); 
                input1.setText(null);
                output1.setText(null);
                combo_input1.setSelectedItem("KODI");
                combo_output1.setSelectedItem("KODI");
            }
        }catch(NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan.\nDilarang menggunakan karakter untuk memasukkan nilai,\ntidak memasukkan apapun,\natau memasukan jumlah diluar batas.");            
                input1.setText(null);
                output1.setText(null);
                combo_input1.setSelectedItem("KODI");
                combo_output1.setSelectedItem("KODI");
        }    
    }

    private void tombol_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMousePressed
        Mnu_Utama objTampilNewJFrame = new Mnu_Utama();
        objTampilNewJFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tombol_balikMousePressed

    private void tombol_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseEntered

    private void tombol_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanJumlah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanJumlah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanJumlah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSatuanJumlah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSatuanJumlah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_input;
    private javax.swing.JComboBox<String> combo_input1;
    private javax.swing.JComboBox<String> combo_output;
    private javax.swing.JComboBox<String> combo_output1;
    private javax.swing.JButton convert_input;
    private javax.swing.JButton convert_input1;
    private javax.swing.JTextField input;
    private javax.swing.JTextField input1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JTextField output;
    private javax.swing.JTextField output1;
    private javax.swing.JButton reset_input;
    private javax.swing.JButton reset_input1;
    private javax.swing.JLabel tombol_balik;
    // End of variables declaration//GEN-END:variables
}
