/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
/**
 *
 * @author Dumasi Ekel
 */
public class KonversiSuhu extends javax.swing.JFrame implements KonversiSuhuInterface {

    /**
     * Creates new form KonversiSatuanPanjang
     */
    public KonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        convert = new javax.swing.JButton();
        tmbl_balik = new javax.swing.JLabel();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("KONVERSI SUHU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 30, 200, 50);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CELCIUS", "KELVIN", "FAHRENHEIT" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(410, 110, 150, 40);

        jComboBox2.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CELCIUS", "KELVIN", "FAHRENHEIT" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(410, 170, 150, 40);

        input.setBackground(new java.awt.Color(254, 254, 214));
        input.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputKeyTyped(evt);
            }
        });
        jPanel1.add(input);
        input.setBounds(40, 110, 340, 40);

        output.setEditable(false);
        output.setBackground(new java.awt.Color(242, 242, 196));
        output.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(output);
        output.setBounds(40, 170, 340, 40);

        convert.setBackground(new java.awt.Color(254, 254, 214));
        convert.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        convert.setText("CONVERT");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });
        jPanel1.add(convert);
        convert.setBounds(330, 240, 130, 40);

        tmbl_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tmbl_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tmbl_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tmbl_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tmbl_balikMousePressed(evt);
            }
        });
        jPanel1.add(tmbl_balik);
        tmbl_balik.setBounds(20, 20, 70, 70);

        reset.setBackground(new java.awt.Color(254, 254, 214));
        reset.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(160, 240, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 300);

        setSize(new java.awt.Dimension(610, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        //KonversiSatuanPanjang obj = new KonversiSatuanPanjang();
        //obj.prosesKonversiSatuanPanjang
        prosesKonversiSuhu();
    }//GEN-LAST:event_convertActionPerformed
    @Override
    public void prosesKonversiSuhu(){
        String statement;
        try{
            statement = input.getText();
            int k = Integer.parseInt(statement);
            /*#1
            ===========================================================================================================
            KEMBALI KE DIRI MASING MASING
            ==============================================================================================================
            */
            if(jComboBox1.getSelectedItem().equals("CELCIUS") && jComboBox2.getSelectedItem().equals("CELCIUS")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("KELVIN") && jComboBox2.getSelectedItem().equals("KELVIN")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            else if(jComboBox1.getSelectedItem().equals("FAHRENHEIT") && jComboBox2.getSelectedItem().equals("FAHRENHEIT")){
                String hasil = String.format("%d", k);
                output.setText(hasil);
            }        
            /*#2
            ===========================================================================================================
            CELCIUS ==> SEMUA 
            ==============================================================================================================
            */
            else if(jComboBox1.getSelectedItem().equals("CELCIUS") && jComboBox2.getSelectedItem().equals("KELVIN")){
                double hasil2 = k * 274.15f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("CELCIUS") && jComboBox2.getSelectedItem().equals("FAHRENHEIT")){
                double hasil2 = k * 33.8f;
                String hasil = String.format("%f", hasil2);
                output.setText(hasil);
            }
            /*#3
            ============================================================================================================
            KELVIN ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("KELVIN") && jComboBox2.getSelectedItem().equals("FAHRENHEIT")){
                double hasil1 = k * -457.87f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("KELVIN") && jComboBox2.getSelectedItem().equals("CELCIUS")){
                double hasil1 = k * -272.15f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            /*#4
            ============================================================================================================
            FAHRENHEIT ==> SEMUA   
            ============================================================================================================        
            */
            else if(jComboBox1.getSelectedItem().equals("FAHRENHEIT") && jComboBox2.getSelectedItem().equals("CELCIUS")){
                double hasil1 = k * -17.2222f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else if(jComboBox1.getSelectedItem().equals("FAHRENHEIT") && jComboBox2.getSelectedItem().equals("KELVIN")){
                double hasil1 = k * 255.928f;
                String hasil = String.format("%f", hasil1);
                output.setText(hasil);
            }
            else{
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan."); 
                input.setText(null);
                output.setText(null);
                jComboBox1.setSelectedItem("KM");
                jComboBox2.setSelectedItem("KM");
            }
        }catch(NumberFormatException a){
                JOptionPane.showMessageDialog(null, "Terjadi Permasalahan.\nDilarang menggunakan karakter untuk memasukkan nilai,\ntidak memasukkan apapun,\natau memasukan jumlah diluar batas.");            
                input.setText(null);
                output.setText(null);
                jComboBox1.setSelectedItem("KM");
                jComboBox2.setSelectedItem("KM");
        }
/*

=================================================(PEMISAH)==========================================================        
     
*/
    
    }
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        input.setText(null);
        output.setText(null);
        jComboBox1.setSelectedItem("KM");
        jComboBox2.setSelectedItem("KM");
    }//GEN-LAST:event_resetActionPerformed

    private void inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKeyPressed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed

        
    }//GEN-LAST:event_inputActionPerformed

    private void tmbl_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbl_balikMousePressed
        Mnu_Utama objTampilNewJFrame = new Mnu_Utama();
        objTampilNewJFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tmbl_balikMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tmbl_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbl_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tmbl_balik.setIcon(II);
    }//GEN-LAST:event_tmbl_balikMouseEntered

    private void tmbl_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbl_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tmbl_balik.setIcon(II);
    }//GEN-LAST:event_tmbl_balikMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JTextField input;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField output;
    private javax.swing.JButton reset;
    private javax.swing.JLabel tmbl_balik;
    // End of variables declaration//GEN-END:variables
}
