/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;
import javax.swing.ImageIcon;
/**
 *
 * @author Dumasi Ekel
 */
public class OTHERS extends javax.swing.JFrame {

    /**
     * Creates new form OTHERS
     */
    public OTHERS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        tombo_balik = new javax.swing.JLabel();
        pilihan = new javax.swing.JComboBox<>();
        tombol_klik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.setLayout(null);

        judul.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 153, 51));
        judul.setText("  OTHERS");
        jPanel1.add(judul);
        judul.setBounds(160, 40, 99, 33);

        tombo_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tombo_balik.setToolTipText("");
        tombo_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombo_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombo_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombo_balikMousePressed(evt);
            }
        });
        jPanel1.add(tombo_balik);
        tombo_balik.setBounds(20, 20, 64, 64);

        pilihan.setBackground(new java.awt.Color(254, 254, 214));
        pilihan.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        pilihan.setForeground(new java.awt.Color(255, 153, 51));
        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH SALAH SATU ..", "TENTANG", "BILANGAN PRIMA", "SUBNETTING" }));
        pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanActionPerformed(evt);
            }
        });
        jPanel1.add(pilihan);
        pilihan.setBounds(80, 100, 260, 50);

        tombol_klik.setBackground(new java.awt.Color(254, 254, 214));
        tombol_klik.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        tombol_klik.setText("PILIH");
        tombol_klik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_klikActionPerformed(evt);
            }
        });
        jPanel1.add(tombol_klik);
        tombol_klik.setBounds(150, 170, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(410, 230));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tombo_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombo_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tombo_balik.setIcon(II);
    }//GEN-LAST:event_tombo_balikMouseEntered

    private void tombo_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombo_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tombo_balik.setIcon(II);
    }//GEN-LAST:event_tombo_balikMouseExited

    private void tombo_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombo_balikMousePressed
        Mnu_Utama objTampilMU = new Mnu_Utama();
        objTampilMU.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tombo_balikMousePressed

    private void pilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihanActionPerformed

    private void tombol_klikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_klikActionPerformed
        if(pilihan.getSelectedItem().equals("SUBNETTING")){
            Subnetting objTampilNilai_Subnetting = new Subnetting();
            objTampilNilai_Subnetting.setVisible(true);
            setVisible(false);
        }
        else if(pilihan.getSelectedItem().equals("TENTANG")){
            Tentang tentang = new Tentang();
            tentang.setVisible(true);
            setVisible(false);
        }        
        else if(pilihan.getSelectedItem().equals("BILANGAN PRIMA")){
            BilanganPrima objTampilBilanganPrima = new BilanganPrima();
            objTampilBilanganPrima.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_tombol_klikActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){ 
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try 
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTHERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTHERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTHERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTHERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTHERS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JLabel tombo_balik;
    private javax.swing.JButton tombol_klik;
    // End of variables declaration//GEN-END:variables
}
