/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversifinalproject_prince_oop;

import java.io.BufferedReader;
import javax.swing.ImageIcon;

/**
 *
 * @author George
 */
public class Subnetting extends javax.swing.JFrame {
    
	static String network_id = "200.120.10.";
	static int daftar_subnet = 0;
	static int daftar_subnet2 = 0;
	static String per = "/";
	static int subnetting = 24;
	static String subnet_mask = "255.255.255.";
	static int aw = 256;
	static int jumlah_bit = 32;
	static int pangkat_dasar = 2;
	static int simpan_kelipatan = 0;
    /**
     * Creates new form BilanganPrima
     */
    public Subnetting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tombol_balik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jlh_bit = new javax.swing.JLabel();
        subnet_mask_baru = new javax.swing.JLabel();
        jlh_subnet = new javax.swing.JLabel();
        jkelipatan = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();
        dftr_subnet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jlhh_bit = new javax.swing.JLabel();
        proses_maks_host = new javax.swing.JLabel();
        hasil_maks_host_per_subnet = new javax.swing.JLabel();
        jlh_maks_seluruh_host = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 300));
        jPanel1.setLayout(null);

        tombol_balik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"))); // NOI18N
        tombol_balik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombol_balikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombol_balikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tombol_balikMousePressed(evt);
            }
        });
        jPanel1.add(tombol_balik);
        tombol_balik.setBounds(20, 10, 70, 90);

        jButton1.setBackground(new java.awt.Color(254, 254, 214));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 51));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 160, 90, 30);

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 153, 51));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(254, 254, 214));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("-");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(340, 100, 350, 450);

        jComboBox1.setBackground(new java.awt.Color(254, 254, 214));
        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 153, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Bit", "2 Bit", "3 Bit", "5 Bit", "6 Bit" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(50, 110, 140, 40);

        jlh_bit.setText("-");
        jPanel1.add(jlh_bit);
        jlh_bit.setBounds(40, 210, 280, 14);

        subnet_mask_baru.setText("-");
        jPanel1.add(subnet_mask_baru);
        subnet_mask_baru.setBounds(40, 230, 280, 14);

        jlh_subnet.setText("-");
        jPanel1.add(jlh_subnet);
        jlh_subnet.setBounds(40, 250, 280, 14);

        jkelipatan.setText("-");
        jPanel1.add(jkelipatan);
        jkelipatan.setBounds(40, 270, 280, 14);

        keterangan.setText("-");
        jPanel1.add(keterangan);
        keterangan.setBounds(40, 290, 280, 14);

        dftr_subnet.setText("-");
        jPanel1.add(dftr_subnet);
        dftr_subnet.setBounds(40, 310, 280, 20);

        jTextArea2.setBackground(new java.awt.Color(254, 254, 214));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea2.setRows(5);
        jTextArea2.setText("-");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 330, 280, 140);

        jlhh_bit.setText("-");
        jPanel1.add(jlhh_bit);
        jlhh_bit.setBounds(40, 480, 280, 14);

        proses_maks_host.setText("-");
        jPanel1.add(proses_maks_host);
        proses_maks_host.setBounds(40, 500, 280, 14);

        hasil_maks_host_per_subnet.setText("-");
        jPanel1.add(hasil_maks_host_per_subnet);
        hasil_maks_host_per_subnet.setBounds(40, 520, 280, 14);

        jlh_maks_seluruh_host.setText("-");
        jPanel1.add(jlh_maks_seluruh_host);
        jlh_maks_seluruh_host.setBounds(40, 540, 280, 14);

        judul.setFont(new java.awt.Font("Tempus Sans ITC", 0, 30)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 153, 51));
        judul.setText("SUBNETTING");
        jPanel1.add(judul);
        judul.setBounds(270, 40, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(711, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tombol_balikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik2.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseEntered

    private void tombol_balikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/gambar_JPEG/Kiribalik.png"));
        tombol_balik.setIcon(II);
    }//GEN-LAST:event_tombol_balikMouseExited

    private void tombol_balikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_balikMousePressed
        OTHERS objTampilNewJFrame = new OTHERS();
        objTampilNewJFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tombol_balikMousePressed

    public void prosesSubnetting(){
        //clear();
        if(jComboBox1.getSelectedItem().equals("1 Bit")){
            //clear();
            int d = 128;
            hitungSubnetting(d, 1);
        }
        else if(jComboBox1.getSelectedItem().equals("2 Bit")){
            clear();
            int p = 192;
            hitungSubnetting(p, 2);
        }
        else if(jComboBox1.getSelectedItem().equals("3 Bit")){
            clear();
            int h = 224;
            hitungSubnetting(h, 3);
        }
        else if(jComboBox1.getSelectedItem().equals("5 Bit")){
            clear();
            int o = 248;
            hitungSubnetting(o, 5);
        }
        else if(jComboBox1.getSelectedItem().equals("6 Bit")){
            clear();
            int l = 252;
            hitungSubnetting(l, 6);
        }        
    }
    public void hitungSubnetting(int f, int jlhSub){
        String awkrd= ""; String awkrd1 = "";
        jlh_bit.setText("====== " + jlhSub + " bit ======");
        subnet_mask_baru.setText("1.Subnet Mask Baru:" + subnet_mask + f);
        int jlhSubnet = (int)Math.pow(pangkat_dasar, jlhSub);
        jlh_subnet.setText("2.Jlh subnet: " + pangkat_dasar + " pangkat "+ jlhSub+ " = "+ jlhSubnet +"subnet");
        int kelipatan = aw - f; int pangkat1 = 1; int hasil2, hasil3;
        simpan_kelipatan = kelipatan;
        int kelipatan_sblm = kelipatan;
        jkelipatan.setText("3.Kelipatan subnet:" + kelipatan);
        keterangan.setText("Jadi ada " + jlhSubnet +" subnet dengan kelipatan "+ kelipatan);
        dftr_subnet.setText("4.Daftar Subnet");
	hasil2 = subnetting;
	hasil3 = hasil2 + jlhSub;
	for(int i = 0; i < jlhSubnet ; i++){
            awkrd = awkrd + (i+1) + ". " + network_id + daftar_subnet + per + hasil3 + "\n";
            jTextArea2.setText(awkrd);
            daftar_subnet += kelipatan;
	}
        int jlh_bit = jumlah_bit - hasil3;
        int h = (int)Math.pow(pangkat_dasar, jlh_bit);
        jlhh_bit.setText("5. - Jumlah bit utk host ID : " + jlh_bit);
        proses_maks_host.setText("-Maks host tiap subnet: "+ h +" - "+ pangkat_dasar);
        int maks_host = h - pangkat_dasar;
        hasil_maks_host_per_subnet.setText("= "+maks_host);
        int jlhMaksH = maks_host * h;
        jlh_maks_seluruh_host.setText("-Jumlah maksimal seluruh host: " + jlhMaksH);
        for(int j = 0; j < jlhSubnet; j++){
        int daftar_subnett = daftar_subnet2+1;
	int klptnKurang2 = kelipatan - 2;
	int klptnKurang1 = kelipatan - 1;
        awkrd1 = awkrd1 + "\nSubnet ke - " + (j+1) + "\n-Network ID :" +  network_id + daftar_subnet2 + per + hasil3 + "\n-Range IP Address: " + network_id + daftar_subnett + " s/d " + network_id + klptnKurang2 + "\n-Broadcast address: " + network_id +  klptnKurang1 + "\n-Subnetmask: " + subnet_mask + f + "\n";
	jTextArea1.setText(awkrd1);
        daftar_subnet2 = klptnKurang1+1;
	simpan_kelipatan = simpan_kelipatan + kelipatan_sblm;
	kelipatan = simpan_kelipatan;
        }    
    }
    public void clear(){
        jlh_bit.setText(null);
        subnet_mask_baru.setText(null);
        jlh_subnet.setText(null);
        jkelipatan.setText(null);
        keterangan.setText(null);
        dftr_subnet.setText(null);
        jlhh_bit.setText(null);
        tombol_balik.setText(null);
        jlh_maks_seluruh_host.setText(null);
	network_id = "200.120.10.";
	daftar_subnet = 0;
	daftar_subnet2 = 0;
	per = "/";
	subnetting = 24;
	subnet_mask = "255.255.255.";
	aw = 256;
	jumlah_bit = 32;
	pangkat_dasar = 2;
	simpan_kelipatan = 0;        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        prosesSubnetting();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i = 0.0; i <= 1.0; i = i + 0.1){ 
            String val = i + "F";
            float f = Float.valueOf(val);  
            this.setOpacity(f);       
            try 
            {
                Thread.sleep(100); 
            }
            catch(Exception e)
            {
            
            }
        }
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subnetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subnetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subnetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subnetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subnetting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dftr_subnet;
    private javax.swing.JLabel hasil_maks_host_per_subnet;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel jkelipatan;
    private javax.swing.JLabel jlh_bit;
    private javax.swing.JLabel jlh_maks_seluruh_host;
    private javax.swing.JLabel jlh_subnet;
    private javax.swing.JLabel jlhh_bit;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel proses_maks_host;
    private javax.swing.JLabel subnet_mask_baru;
    private javax.swing.JLabel tombol_balik;
    // End of variables declaration//GEN-END:variables
}
